[package]
name = "tmi-rs"
version = "0.1.0"
authors = ["Stefan Kaufhold <stefan@skaufhold.de>"]
edition = "2018"

[dependencies]
log = "0.4.8"
fnv = "1.0.6"
derive_builder = "0.8.0"
futures-preview = "0.3.0-alpha.19"
tokio-io = "0.2.0-alpha.6"
async-trait = "0.1.13"
url = "2.1.0"
nom = "5.0.1"

[lib]
name = "tmi_rs"

[dependencies.tokio-tungstenite]
git = "https://github.com/dbcfd/tokio-tungstenite.git"
branch = "tokio2"