[package]
name = "tmi-rs"
version = "0.1.0"
authors = ["Stefan Kaufhold <cere@fastmail.fm>"]
edition = "2018"

[dependencies]
ws = { version = "0.8.0", features = ["ssl"] }
log = "0.4.6"

[lib]
name = "tmi_rs"